# fly.toml app configuration file generated for chauffe-coming-soon on 2025-10-03T17:18:52-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chauffe-coming-soon'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[http_service.checks]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "http"
  timeout = "2s"

[env]
  DEBUG = "false"
  DJANGO_SETTINGS_MODULE = "mychauffe.settings"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
