# Generated by Django 4.2.24 on 2025-10-13 16:12

from django.db import migrations, models
import uuid


def generate_uuids_for_existing_profiles(apps, schema_editor):
    """Generate unique UUIDs for existing UserProfile instances"""
    UserProfile = apps.get_model('core', 'UserProfile')
    for profile in UserProfile.objects.all():
        profile.uuid = uuid.uuid4()
        profile.save()


def reverse_generate_uuids(apps, schema_editor):
    """Reverse operation - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        # First add the field without unique constraint
        migrations.AddField(
            model_name="userprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Generate UUIDs for existing records
        migrations.RunPython(
            generate_uuids_for_existing_profiles,
            reverse_generate_uuids,
        ),
        # Now alter the field to make it unique and not null
        migrations.AlterField(
            model_name="userprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
