# Generated by Django 4.2.24 on 2025-10-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="blockchain_references",
            field=models.TextField(blank=True, default="{}"),
        ),
    ]
