# Generated by Django 4.2.24 on 2025-10-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile_blockchain_references"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="core.order",
            ),
        ),
    ]
